services:
  nginx:
    image: "nginx:1.25.5-alpine"
    ports:
      - "8580:80"
    networks:
      - outer
      - inner
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - compiled-frontend:/var/www/mnt
  frontend:
    build: ./frontend
    volumes:
      - compiled-frontend:/opt/build/resources/public
  backend:
    build: ./backend
    environment:
      - "SHT_DB_HOST=db:5432"
      - "SHT_DB_USER=postgres"
      - "SHT_DB_PASSWORD=pgpassword"
      - "ASPNETCORE_URLS=http://+:8680"
    networks:
      - inner
  db: # without persistance for now
    image: "postgres:16.2"
    environment:
      - "POSTGRES_PASSWORD=pgpassword"
    networks:
      - inner

networks:
  outer:
  inner:

volumes:
  compiled-frontend:
