services:
  frontend:
    build: ./frontend
    ports:
      - "8580:80"
    networks:
      - outer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  backend:
    build: ./backend
    environment:
      - "SHT_DB_HOST=db:5432"
      - "SHT_DB_USER=postgres"
      - "SHT_DB_PASSWORD=pgpassword"
      - "ASPNETCORE_URLS=http://+:8680"
    networks:
      - inner
      - outer
  db:
    image: "postgres:16.2"
    environment:
      - "POSTGRES_PASSWORD=pgpassword"
    networks:
      - inner
    volumes:
      - ./sht-postgres-data:/var/lib/postgresql/data

networks:
  outer:
  inner:
